name: Python 3.7
on: 
 # Trigger the workflow on push or pull request,
 # but only for the main branch
 push:
  branches:
   - main
jobs:
  build:
    runs-on: ubuntu-latest 
    # windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.5.10
    - name: Install dependencies
      run: |
        make install
    - name: Lint
      run: |
        make lint
    - name: Test
      run: |
        make test
